"""initial schema

Revision ID: 187b7cae8814
Revises:
Create Date: 2026-06-25 23:07:05.868916
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '187b7cae8814'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_team'), ['team'], unique=False)

    op.create_table('api_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('key_prefix', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('client_host', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_log', schema=None) as batch_op:
        batch_op.create_index('ix_usage_key_ts', ['api_key_id', 'ts'], unique=False)

    op.create_table('daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('solar_mwh', sa.Float(), nullable=False),
    sa.Column('wind_mwh', sa.Float(), nullable=False),
    sa.Column('total_mwh', sa.Float(), nullable=False),
    sa.Column('solar_peak_mw', sa.Float(), nullable=False),
    sa.Column('wind_peak_mw', sa.Float(), nullable=False),
    sa.Column('total_peak_mw', sa.Float(), nullable=False),
    sa.Column('solar_cuf', sa.Float(), nullable=False),
    sa.Column('wind_cuf', sa.Float(), nullable=False),
    sa.Column('hybrid_cuf', sa.Float(), nullable=False),
    sa.Column('solar_specific_yield', sa.Float(), nullable=False),
    sa.Column('blocks_count', sa.Integer(), nullable=False),
    sa.Column('data_mode', sa.String(length=32), nullable=False),
    sa.Column('data_label', sa.String(length=32), nullable=False),
    sa.Column('data_quality_status', sa.String(length=24), nullable=False),
    sa.Column('simulation_version', sa.String(length=32), nullable=False),
    sa.Column('model_assumption_version', sa.String(length=32), nullable=False),
    sa.Column('plant_config_version', sa.Integer(), nullable=False),
    sa.Column('weather_source', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_code', 'sim_date', 'data_mode', 'simulation_version', 'model_assumption_version', name='uq_daily_summary')
    )
    with op.batch_alter_table('daily_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_summary_plant_code'), ['plant_code'], unique=False)
        batch_op.create_index('ix_summary_plant_date_cur', ['plant_code', 'sim_date', 'is_current'], unique=False)

    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('block_start', sa.DateTime(), nullable=False),
    sa.Column('block_end', sa.DateTime(), nullable=False),
    sa.Column('solar_mw', sa.Float(), nullable=False),
    sa.Column('solar_mwh', sa.Float(), nullable=False),
    sa.Column('wind_mw', sa.Float(), nullable=False),
    sa.Column('wind_mwh', sa.Float(), nullable=False),
    sa.Column('total_mw', sa.Float(), nullable=False),
    sa.Column('total_mwh', sa.Float(), nullable=False),
    sa.Column('solar_cuf', sa.Float(), nullable=False),
    sa.Column('wind_cuf', sa.Float(), nullable=False),
    sa.Column('hybrid_cuf', sa.Float(), nullable=False),
    sa.Column('solar_status', sa.String(length=24), nullable=False),
    sa.Column('wind_status', sa.String(length=24), nullable=False),
    sa.Column('data_mode', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('data_label', sa.String(length=32), nullable=False),
    sa.Column('data_quality_status', sa.String(length=24), nullable=False),
    sa.Column('simulation_version', sa.String(length=32), nullable=False),
    sa.Column('model_assumption_version', sa.String(length=32), nullable=False),
    sa.Column('plant_config_version', sa.Integer(), nullable=False),
    sa.Column('weather_source', sa.String(length=64), nullable=False),
    sa.Column('weather_fetch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weather_model_used', sa.String(length=64), nullable=True),
    sa.Column('forecast_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_code', 'sim_date', 'block_no', 'data_mode', 'simulation_version', 'model_assumption_version', name='uq_generation_block')
    )
    with op.batch_alter_table('generation_block', schema=None) as batch_op:
        batch_op.create_index('ix_gen_plant_date_mode_cur', ['plant_code', 'sim_date', 'data_mode', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_block_plant_code'), ['plant_code'], unique=False)

    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('plant_name', sa.String(length=255), nullable=False),
    sa.Column('active_config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_plant_code'), ['plant_code'], unique=True)

    op.create_table('raw_weather_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('data_mode', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_weather_response', schema=None) as batch_op:
        batch_op.create_index('ix_raw_plant_date_mode', ['plant_code', 'sim_date', 'data_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_weather_response_plant_code'), ['plant_code'], unique=False)

    op.create_table('simulation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('data_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('blocks_written', sa.Integer(), nullable=False),
    sa.Column('simulation_version', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_run_plant_code'), ['plant_code'], unique=False)

    op.create_table('simulation_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_assumption_version', sa.String(length=32), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('weather_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('block_start', sa.DateTime(), nullable=False),
    sa.Column('block_end', sa.DateTime(), nullable=False),
    sa.Column('data_mode', sa.String(length=32), nullable=False),
    sa.Column('weather_source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interpolated', sa.Boolean(), nullable=False),
    sa.Column('ghi', sa.Float(), nullable=True),
    sa.Column('poa', sa.Float(), nullable=True),
    sa.Column('dni', sa.Float(), nullable=True),
    sa.Column('dhi', sa.Float(), nullable=True),
    sa.Column('temperature_2m', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('is_day', sa.Integer(), nullable=True),
    sa.Column('wind_speed_10m', sa.Float(), nullable=True),
    sa.Column('wind_speed_100m', sa.Float(), nullable=True),
    sa.Column('wind_speed_120m', sa.Float(), nullable=True),
    sa.Column('wind_speed_180m', sa.Float(), nullable=True),
    sa.Column('wind_direction_100m', sa.Float(), nullable=True),
    sa.Column('wind_gusts_10m', sa.Float(), nullable=True),
    sa.Column('surface_pressure', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_code', 'sim_date', 'block_no', 'data_mode', name='uq_weather_block')
    )
    with op.batch_alter_table('weather_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_block_plant_code'), ['plant_code'], unique=False)
        batch_op.create_index('ix_weather_plant_date_mode', ['plant_code', 'sim_date', 'data_mode'], unique=False)

    op.create_table('weather_provider_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('forecast_url', sa.String(length=512), nullable=False),
    sa.Column('historical_forecast_url', sa.String(length=512), nullable=False),
    sa.Column('archive_url', sa.String(length=512), nullable=False),
    sa.Column('solar_variables', sa.JSON(), nullable=False),
    sa.Column('wind_variables', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plant_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plant_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('solar_ac_mw', sa.Float(), nullable=False),
    sa.Column('solar_dc_mw', sa.Float(), nullable=False),
    sa.Column('dc_ac_ratio', sa.Float(), nullable=False),
    sa.Column('solar_performance_ratio', sa.Float(), nullable=False),
    sa.Column('solar_loss_factor', sa.Float(), nullable=False),
    sa.Column('temp_coeff_pct_per_c', sa.Float(), nullable=False),
    sa.Column('panel_tilt', sa.Float(), nullable=False),
    sa.Column('panel_azimuth', sa.Float(), nullable=False),
    sa.Column('use_global_tilted_irradiance', sa.Boolean(), nullable=False),
    sa.Column('wind_ac_mw', sa.Float(), nullable=False),
    sa.Column('wind_loss_factor', sa.Float(), nullable=False),
    sa.Column('wind_power_curve', sa.JSON(), nullable=False),
    sa.Column('curve_rated_kw', sa.Float(), nullable=False),
    sa.Column('hub_height_m', sa.Float(), nullable=False),
    sa.Column('cut_in_ms', sa.Float(), nullable=False),
    sa.Column('rated_ms', sa.Float(), nullable=False),
    sa.Column('cut_out_ms', sa.Float(), nullable=False),
    sa.Column('air_density_correction', sa.Boolean(), nullable=False),
    sa.Column('block_minutes', sa.Integer(), nullable=False),
    sa.Column('api_access_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_code', 'config_version', name='uq_plant_config_version')
    )
    with op.batch_alter_table('plant_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_config_plant_code'), ['plant_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_config_plant_code'))

    op.drop_table('plant_config')
    op.drop_table('weather_provider_config')
    with op.batch_alter_table('weather_block', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_plant_date_mode')
        batch_op.drop_index(batch_op.f('ix_weather_block_plant_code'))

    op.drop_table('weather_block')
    op.drop_table('simulation_version')
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_run_plant_code'))

    op.drop_table('simulation_run')
    with op.batch_alter_table('raw_weather_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_weather_response_plant_code'))
        batch_op.drop_index('ix_raw_plant_date_mode')

    op.drop_table('raw_weather_response')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_plant_code'))

    op.drop_table('plant')
    with op.batch_alter_table('generation_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_block_plant_code'))
        batch_op.drop_index('ix_gen_plant_date_mode_cur')

    op.drop_table('generation_block')
    op.drop_table('error_log')
    with op.batch_alter_table('daily_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_summary_plant_date_cur')
        batch_op.drop_index(batch_op.f('ix_daily_summary_plant_code'))

    op.drop_table('daily_summary')
    with op.batch_alter_table('api_usage_log', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_key_ts')

    op.drop_table('api_usage_log')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_team'))
        batch_op.drop_index(batch_op.f('ix_api_key_key_prefix'))

    op.drop_table('api_key')
    # ### end Alembic commands ###
